### ISSUE TITLE
syntax error in HeaderFlags definitions

### ISSUE THREAD

**Issue by philhagen** [EricZimmerman/Lnk#2]
https://github.com/EricZimmerman/Lnk/blob/9eddcba77e71acf502921f97c9c786dd1d6bdade/Lnk/Header.cs#L32

I think this line has an error - it's not consistent with the other definitions (but I'm not smart enough to know for sure...)

**Comment by EricZimmerman** [comment]
That description is right from Microsoft's documentation

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-shllink/ae350202-3ba9-4790-9e9e-98935f4ee5af

**Comment by philhagen** [comment]
yes, but the syntax for that line is wacky.....  shouldn't it be more like:

` [Description("The file system location is represented in the shell namespace when the path to an item is parsed into the link target identifiers")] NoPidlAlias = 0x00008000,`

There is no equal sign before the value and it's spread across 3 lines.

**Comment by philhagen** [comment]
as-is, the lines are this:
![2019-04-15_10-28-55](https://user-images.githubusercontent.com/428886/56140644-48da9480-5f69-11e9-90d6-e52aa056749a.png)

**Comment by EricZimmerman** [comment]
ah now i see. the wrapping is ok, but the missing = i will fix now

**Comment by EricZimmerman** [comment]
fixed!

**Comment by EricZimmerman** [comment]
added the = and updated the format of the value. lemme know if theres something else and i can reopen. thanks for finding this!
