### ISSUE TITLE
Properties LocalPath and CommonPath

### ISSUE THREAD

**Issue by voidray** [EricZimmerman/Lnk#7]
How should the properties LocalPath and CommonPath be used? First I used LocalPath to get the target link of a linked directory, but then I saw that sometimes it isn't the full path. In my tests in was for example "D:\\" and CommonPath contained the rest of the path.
I'm not sure why this applies only to a few of the directory link files. Maybe it has to do with the OS version they were created?! (Windows 7/8.1 instead of 10)
For now I use Path.Combine to combine those two. Is this the correct way? I didn't see a property that always contains the full target path.

**Comment by EricZimmerman** [comment]
sounds like you have it figured, but you can look at LECmd code to see how i do it. your other option is to build out the absolute path via the shellitems, like LECmd does.
