### ISSUE TITLE
Parsing error on Malicious LNK Files (or Arbitrary Corrupted LNK files)

### ISSUE THREAD

**Issue by SteAmeR** [EricZimmerman/Lnk#8]
Hi Eric,

Today, I came across a new malicious lnk file and want to analyze it by "LNK" project. However, the sample throws exceptions while looping on lines of "extrabyte" code. I have attached a screenshot that includes of issue.  Such malicious files are becoming more and more common and code fixing is essential to fighting them, and thank you in advance as well for your help and knowledge.

![arithmeticissue](https://user-images.githubusercontent.com/399791/185717619-c5e3f2a1-702f-4aba-8546-330c0e22cffb.PNG)

Download link for Malicious LNK sample: https://api.docguard.io:8443/Downloads/a92c49ff-6014-4b23-9f0a-733cc0f643cf/fe8fd4a9a8105b9052f2d29ab493613c69e1c6b3a8d34ee57c0c4e92b4fe483d.zip
Zip Password: infected

Regards,

**Comment by SteAmeR** [comment]
Hi Eric,

Well, are you planning on making a "Nuget" transfer soon related to these fixes?

Regards,

**Comment by EricZimmerman** [comment]
just pushed it
